apiVersion: v1
kind: Pod
metadata:
  name: microservice-one-health-pod
spec:
  containers:
  - image: microservice-one-health-image:latest
    imagePullPolicy: IfNotPresent
    name: microservice-one-health-container
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: 8080
